services:
  fair_teams:
    build: .
    container_name: fair_teams
    restart: on-failure:3
    env_file:
      - .env
  
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    env_file:
      - .env